### ISSUE TITLE
Four.Context is not a function

### ISSUE THREAD

**Issue by philmaker1** [allotrop3/four#35]
When I download Four and try to run any of the examples, they don't run. I see the message in the console "Four.Context is not a function".

The hosted example at http://allotrop3.github.io/four/ runs fine.

**Comment by allotrop3** [comment]
Hi @philmaker1

Sorry for the late reply and thanks for checking out Four!

The examples you are referring to, are they the ones currently in the repository? If so, they run on v0.3b of Four which is currently being worked on (the examples update as I add new features and so forth to the framework). You can get v0.3b by forking the repo and compiling the source - I've added a Contribute page to the wiki - https://github.com/allotrop3/four/wiki/Contributing. Instead of `gulp watch`, run `gulp build`. This will generate v0.3b in the `dist/` folder and the examples should then run. Note v0.3b is quite different from the docs in the wiki as I'm working on a new website for Four that will include better, and up-to-date, docs and will be part of v0.3 release. The current wiki is for v0.2.

Hope this helps!
